version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: expense-tracker-postgres-staging
    restart: always
    environment:
      POSTGRES_DB: expense_db
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expense_user -d expense_db -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    image: ashybaiev/expense-tracker-backend:staging
    container_name: expense-tracker-backend-staging
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/expense_db
      SPRING_DATASOURCE_USERNAME: expense_user
      SPRING_DATASOURCE_PASSWORD: expense_pass
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: ashybaiev/expense-tracker-frontend:staging
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    volumes:
      - ./expense-tracker-frontend/nginx.conf.staging:/etc/nginx/conf.d/nginx.conf:ro

volumes:
  pg_data:
