name: CI Pipeline

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build backend
        run: mvn -B clean verify --file expense-tracker-backend/pom.xml

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: expense-tracker-frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: expense-tracker-frontend

      - name: Build frontend
        run: npm run build --if-present
        working-directory: expense-tracker-frontend

      - name: Run backend tests
        run: mvn test --file expense-tracker-backend/pom.xml


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # push to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/expense-tracker-backend ./expense-tracker-backend
          docker push ${{ secrets.DOCKER_USERNAME }}/expense-tracker-backend

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/expense-tracker-frontend ./expense-tracker-frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/expense-tracker-frontend
